name: Deploy Function to Azure Function App

on:
  workflow_dispatch:
  push:
    branches: [main] # Aggiunto trigger automatico su push nel branch main
    paths:
      - "src/**" # Trigger solo quando ci sono modifiche nel codice sorgente
      - "package.json"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: production # Aggiunto environment per migliore gestione dei segreti

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Aggiornato alla v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20 LTS"
          cache: "npm" # Aggiunto caching per velocizzare il build

      - name: Install dependencies
        run: npm ci

      # - name: Run tests # Aggiunto step per i test
      #  run: npm test

      # ... resto del file invariato ...
      - name: Build Function
        run: npm run build # Assicurati di avere questo script nel package.json

      - name: Create ZIP package (revised)
        run: |
          mkdir release
          cp -r src/Helloworld/* release/  # Ensure all files from src/Helloworld are copied
          cp package.json release/
          cp package-lock.json release/
          cd release
          zip -r ../release.zip ./*

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }} # Spostato in un secret
          package: release.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
