name: Plan Terraform to Azure

on:
  workflow_dispatch:

jobs:

  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Validate Terraform
        working-directory: infra
        run: terraform validate

      - name: Plan Terraform
        working-directory: infra
        run: terraform plan